version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: litecoin_electrumx_gui
      APP_PORT: 80

  litecoin_electrumx:
    image: lukechilds/electrumx:v1.16.0@sha256:2949784536f8f85af229004e12e5b5c3a1d7428918a492f77b4e958035c2ae2a
    container_name: litecoin_electrumx
    restart: always
    init: true
    environment:
      DAEMON_URL: "http://testuser:testpass@litecoin:9332"
      COIN: "Litecoin"
      # https://github.com/spesmilo/electrumx/blob/master/electrumx/lib/coins.py
      NET: mainnet
    volumes:
      - "${APP_DATA_DIR}/data/electrumx:/data"
    ports:
      - "${LITECOIN_ELECTRUMX_NODE_PORT}:${LITECOIN_ELECTRUMX_NODE_PORT}"
    networks:
      default:
        ipv4_address: $LITECOIN_ELECTRUMX_NODE_IP

  litecoin_electrumx_gui:
    image: notrin7/litecoin_electrumx_gui:1.0.0
    container_name: litecoin_electrumx_gui
    restart: always