version: '3'

services:
  app_proxy:
    environment:
      APP_HOST: crafty
      APP_PORT: 8000

  crafty:
    container_name: crafty
    image: registry.gitlab.com/crafty-controller/crafty-4:latest
    restart: always
    environment:
        - TZ=Berlin/Europe
    volumes:
        - ${APP_DATA_DIR}/backups:/crafty/backups
        - ${APP_DATA_DIR}/logs:/crafty/logs
        - ${APP_DATA_DIR}/servers:/crafty/servers
        - ${APP_DATA_DIR}/app/config:/crafty/app/config
        - ${APP_DATA_DIR}/import:/crafty/import